### PR TITLE
route bugfix

### PR DESCRIPTION
**Pull request by bkrrrr**
fix for route(s).
console output is still a kind of buggy

### CODE REVIEW

**Comment by whitecolor** [comment]
routes are parsed last with intention, what kind of problem with route do you have?

**Comment by bkrrr** [comment]
they are parsed after the file read, so the parsing had no effect on the
read operation;

**Comment by whitecolor** [comment]
what route doesn't work?

**Comment by bkrrr** [comment]
for example that one from the doc, its serving the file /mobile and not
/client/mobile/index.html


  route: [
        {'/mobile': '/client/mobile/index.html'}
]

**Comment by whitecolor** [comment]
I have currently the same config in my project and it serves as expected:
```
[ExpressApp] Route match /mobile /client/mobile/index.html /mobile/
[ExpressApp] Client script injected in /client/mobile/index.html
```

**Pull request closed without merging**
